// theme/dark_theme.slint
import { RDSTheme } from "theme.slint";

export global DarkTheme {
    out property <RDSTheme> values: {
        background_main: #1c1c22,
        background_raised: #2a2a35,
        border_subtle: #2a2a35,
        border_strong: #3a3a45,
        text_primary: #f6f1ff,
        text_secondary: #b8b2c7,
        accent_primary: #c53bff,
        accent_secondary: #4A0D7A,
        accent_highlight: #e3c1ff,
        meter_normal: #00ff00,
        meter_warning: #ffd500,
        meter_clip: #ff2d2d,
        radius_small: 2px,
        radius_medium: 4px,
        radius_large: 6px,
        font_small: 12px,
        font_medium: 14px
    };
}
